### ISSUE TITLE
Is there an Update to handle dicts as input?

### ISSUE THREAD

**Issue by AEM90** [ivanbicalho/python-docx-replace#2]
Have you developped an Update which uses **python-docx-replace(doc, dict)** ?

Would be awesome

**Comment by ivanbicalho** [comment]
I'm not sure if I got your point, can you give an example? If you want to pass a dict, you can use something like this: 

```
my_dict = {"name":"Ivan", "phone": "123"}
python-docx-replace(doc, **my_dict)
```

**Comment by AEM90** [comment]
Sorry, I wasn't aware of the ** convention. Thank you
