### ISSUE TITLE
Return all keys in a document without knowing them

### ISSUE THREAD

**Issue by SimonF89** [ivanbicalho/python-docx-replace#6]
Hi ivan,
i had an idea to create a generic way to export data from a Django app to a docx file. There for i would need a function which returns me all keys within a document without knowing them.

like:
keys = get_all_keys("document_Name.docx")

Do you have an idea how to get this? Since you are already very familiar with word documents, I thought I could ask you.

**Comment by ivanbicalho** [comment]
Hello! Yeah, there is simple way to do it. You could navigate through the paragraph texts applying a `regex` to get all the keys. I can introduce it for you in a next version. You can create a PR as well, we can do it together.
